# Generated by Django 6.0.2 on 2026-02-25 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_max_shifts_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='led_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
