# Generated by Django 6.0.2 on 2026-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_role_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
