# Generated by Django 6.0.2 on 2026-03-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_claimed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_session_id',
        ),
    ]
