# Generated by Django 6.0.2 on 2026-02-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_waiver_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiver',
            name='zip_code',
        ),
    ]
