# Generated by Django 6.0.2 on 2026-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_checkout_session_id'),
        ('core', '0009_remove_waiver_zip_code'),
    ]

    operations = [
    ]
