# Generated by Django 6.0.2 on 2026-03-22 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260322_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Restricted tickets require a grant to purchase'),
        ),
        migrations.CreateModel(
            name='TicketGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ticket_type', 'user')},
            },
        ),
    ]
